version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    mem_limit: 20m

  web:
   build: ./webfiles
   links:
      - db
   ports:
      - "5000:5000"
   mem_limit: 20m
